/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 import javafx.application.Application;
 import javafx.event.ActionEvent;
 import javafx.event.EventHandler;
 import javafx.scene.Scene;
 import javafx.scene.control.Button;
 import javafx.scene.layout.*;
 import javafx.stage.Stage;
 import javafx.scene.text.Text;
 import javafx.geometry.*;
 import javafx.scene.control.*;
 import javafx.scene.paint.*;
 import javafx.scene.text.*;
 // import java.awt.*;

public class App extends Application {

  private Stage primary = new Stage();

  @Override
  public void start(Stage primaryStage){
    this.primary = primaryStage;
    // Scene login = this.buildLogin();
    Scene todo = this.buildTodo();
    primaryStage.setTitle("Login");
    // primaryStage.setScene(login);
    primaryStage.setScene(todo);
    primaryStage.setResizable(false);
    primaryStage.show();
  }

  private Scene buildLogin(){
    GridPane grid = new GridPane();
    grid.setHgap(7);
    grid.setVgap(7);
    grid.setPadding(new Insets(25,25,25,25));


    Scene login = new Scene(grid, 300, 275);
    login.getStylesheets().add("styles.css");

    Text scenetitle = new Text("Please Login");
    scenetitle.setFont(Font.font("Tahoma", FontWeight.NORMAL, 20));
    Label userName = new Label("Username:");
    TextField usernameInput = new TextField();
    Label password = new Label("Password:");
    PasswordField passwordInput = new PasswordField();

    grid.add(scenetitle, 0,0,2,1);
    grid.add(userName, 0, 1);
    grid.add(usernameInput, 1,1);
    grid.add(password,0,2);
    grid.add(passwordInput,1,2);
    grid.setGridLinesVisible(true);



    Button signInButton = new Button("Sign In");
    HBox hbBtn = new HBox(10);
    hbBtn.setAlignment(Pos.BOTTOM_RIGHT);
    hbBtn.getChildren().add(signInButton);
    grid.add(hbBtn, 1, 4);

    final Text actiontarget = new Text();
    grid.add(actiontarget,1,6);
    signInButton.setOnAction(event ->
    {
      String user = usernameInput.getText();
      String pass = passwordInput.getText();
      if(user.equals("mattalui") && pass.equals("password"))
      {
        Scene todo = this.buildTodo();
        this.primary.setScene(todo);
      }else{
        actiontarget.setFill(Color.FIREBRICK);
        actiontarget.setText("Credentials Incorrect.");
      }
    });
    return login;
  }

  private Scene buildTodo(){
    this.primary.setHeight(600);
    this.primary.setWidth(400);

    GridPane grid = new GridPane();
    grid.setGridLinesVisible(true);
    grid.setHgap(7);
    grid.setVgap(7);
    grid.setPadding(new Insets(25,25,25,25));

    Text scenetitle = new Text("Todo:");
    scenetitle.setFont(Font.font("Tahoma", FontWeight.NORMAL, 20));
    grid.add(scenetitle,0,0,3,1);

    TextField todoInput = new TextField();
    grid.add(todoInput,0,10,2,1);

    Button addButton = new Button("add");
    addButton.setOnAction(event -> {
      System.out.println(todoInput.getText());
    });
    grid.add(addButton, 2, 10);

    Scene todo = new Scene(grid, 300, 275);
    todo.getStylesheets().add("styles.css");
    return todo;
  }
}
